# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dMYjVl7-zsCuY6uJsGjuNfe1FMeaKST

### Guess the Number Game Python Project (computer)
"""

import random

def guess_number(max_range):
    random_number = random.randint(1, max_range)
    attempts = 0

    print(f"Welcome to the Number Guessing Game! 🎮")
    print(f"I'm thinking of a number between 1 and {max_range}. Can you guess it? 🤔")

    while True:
        try:
            guess = int(input(f"Guess a number between 1 and {max_range}: "))
            attempts += 1

            if guess < random_number:
                print("Oops! Too low. Try again! ⬆️")
            elif guess > random_number:
                print("Oops! Too high. Try again! ⬇️")
            else:
                print(f"🎉 Yay, congrats! You've guessed the number {random_number} correctly in {attempts} attempts! 🎉")
                break
        except ValueError:
            print("Please enter a valid number! ❌")

if __name__ == "__main__":
    max_range = 100
    guess_number(max_range)